[nextcloud]
nextcloud-01 ansible_host=185.98.82.7 ansible_port=2201 nextcloud_dmz_ip=192.168.36.11 keepalived_state=MASTER keepalived_priority=110
nextcloud-02 ansible_host=185.98.82.7 ansible_port=2202 nextcloud_dmz_ip=192.168.36.12 keepalived_state=BACKUP keepalived_priority=100

[postgres_primary]
postgres-primary ansible_host=185.98.82.7 ansible_port=2213 postgres_role=primary postgres_internal_ip=192.168.46.13

[postgres_replica]
postgres-replica ansible_host=185.98.82.7 ansible_port=2214 postgres_role=replica postgres_internal_ip=192.168.46.14

[postgres:children]
postgres_primary
postgres_replica

[services]
services-1 ansible_host=185.98.82.7 ansible_port=2215 services_internal_ip=192.168.46.15

[all:vars]
ansible_user=ubuntu
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
