[firewall]
firewall ansible_host=192.168.36.1

[nextcloud]
nextcloud-1 ansible_host=192.168.36.11 keepalived_state=MASTER keepalived_priority=110
nextcloud-2 ansible_host=192.168.36.12 keepalived_state=BACKUP keepalived_priority=100

[postgres]
postgres-1 ansible_host=192.168.46.13 postgres_role=primary
postgres-2 ansible_host=192.168.46.14 postgres_role=replica

[monitor]
monitor ansible_host=192.168.46.15

[spare]
spare ansible_host=192.168.36.16 spare_dmz_ip=192.168.36.16 spare_internal_ip=192.168.46.16 spare_keepalived_state=BACKUP spare_keepalived_priority=90

[all:vars]
ansible_user=vagrant
ansible_ssh_private_key_file=.vagrant/machines/{{ inventory_hostname }}/virtualbox/private_key
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
