# Используется для ручного запуска Ansible. При `vagrant up/provision`
# Vagrant генерирует inventory и SSH-ключи автоматически.
[firewall]
firewall ansible_host=192.168.46.1 ansible_ssh_private_key_file=../.vagrant/machines/firewall/virtualbox/private_key

[nextcloud]
nextcloud-1 ansible_host=192.168.46.11 keepalived_state=MASTER keepalived_priority=110 ansible_ssh_private_key_file=../.vagrant/machines/nextcloud-1/virtualbox/private_key
nextcloud-2 ansible_host=192.168.46.12 keepalived_state=BACKUP keepalived_priority=100 ansible_ssh_private_key_file=../.vagrant/machines/nextcloud-2/virtualbox/private_key

[postgres]
postgres-1 ansible_host=192.168.46.13 postgres_role=primary ansible_ssh_private_key_file=../.vagrant/machines/postgres-1/virtualbox/private_key
postgres-2 ansible_host=192.168.46.14 postgres_role=replica ansible_ssh_private_key_file=../.vagrant/machines/postgres-2/virtualbox/private_key

[monitor]
monitor ansible_host=192.168.46.15 ansible_ssh_private_key_file=../.vagrant/machines/monitor/virtualbox/private_key

[spare]
spare ansible_host=192.168.46.16 spare_ip=192.168.46.16 spare_keepalived_state=BACKUP spare_keepalived_priority=90 ansible_ssh_private_key_file=../.vagrant/machines/spare/virtualbox/private_key

[all:vars]
ansible_user=vagrant
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
