---
- name: Firewall | nftables + routing
  hosts: firewall
  become: true
  roles:
    - role: firewall
  tags: [firewall]

- name: Monitor | NFS + Zabbix + Rsyslog
  hosts: monitor
  become: true
  roles:
    - role: docker
    - role: nfs
      vars:
        nfs_role: server
    - role: zabbix
      vars:
        zabbix_role: server_agent
    - role: rsyslog
      vars:
        rsyslog_role: server
  tags: [monitor]

- name: PostgreSQL Primary
  hosts: postgres-1
  become: true
  roles:
    - role: docker
    - role: postgres
    - role: backup
    - role: zabbix
      vars:
        zabbix_role: agent
    - role: rsyslog
      vars:
        rsyslog_role: client
  tags: [postgres, postgres-primary]

- name: PostgreSQL Replica
  hosts: postgres-2
  become: true
  roles:
    - role: docker
    - role: postgres
    - role: zabbix
      vars:
        zabbix_role: agent
    - role: rsyslog
      vars:
        rsyslog_role: client
  tags: [postgres, postgres-replica]

- name: Nextcloud backends
  hosts: nextcloud
  become: true
  roles:
    - role: docker
    - role: certs
    - role: nfs
      vars:
        nfs_role: client
    - role: nextcloud
    - role: keepalived
    - role: zabbix
      vars:
        zabbix_role: agent
    - role: rsyslog
      vars:
        rsyslog_role: client
  tags: [nextcloud]
