apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: VictoriaLogs
    type: prometheus
    access: proxy
    url: http://victorialogs:9428
    editable: true
