---
- name: Install rsyslog
  apt:
    name: rsyslog
    state: present
    update_cache: true

- name: Copy rsyslog config
  template:
    src: "rsyslog.{{ rsyslog_role }}.conf.j2"
    dest: /etc/rsyslog.d/99-remote.conf
  notify: restart rsyslog

- name: Enable and start rsyslog
  service:
    name: rsyslog
    state: started
    enabled: true
