---
- name: Install nftables
  apt:
    name: nftables
    state: present
    update_cache: true

- name: Copy nftables ruleset
  template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
  notify: reload nftables

- name: Enable and start nftables
  service:
    name: nftables
    state: started
    enabled: true
