Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.define "server" do |server|
    server.vm.hostname = "ras-server"
    server.vm.network "private_network", ip: "192.168.56.10"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/playbook.yml"
    ansible.inventory_path = "ansible/inventory.ini"
    ansible.verbose = "v"
  end
end
