Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  # Приватная сеть
  INTERNAL_NET = "192.168.46"

  nodes = [
    { name: "firewall",    ip: "#{INTERNAL_NET}.1",  memory: 512,  cpus: 1 },
    { name: "nextcloud-1", ip: "#{INTERNAL_NET}.11", memory: 1536, cpus: 1 },
    { name: "nextcloud-2", ip: "#{INTERNAL_NET}.12", memory: 1536, cpus: 1 },
    { name: "postgres-1",  ip: "#{INTERNAL_NET}.13", memory: 1024, cpus: 1 },
    { name: "postgres-2",  ip: "#{INTERNAL_NET}.14", memory: 1024, cpus: 1 },
    { name: "monitor",     ip: "#{INTERNAL_NET}.15", memory: 2048, cpus: 2 },
    { name: "spare",       ip: "#{INTERNAL_NET}.16", memory: 2048, cpus: 2 },
  ]

  nodes.each do |node|
    config.vm.define node[:name] do |vm|
      vm.vm.hostname = node[:name]
      vm.vm.network "private_network", ip: node[:ip]

      vm.vm.provider "virtualbox" do |vb|
        vb.name   = node[:name]
        vb.memory = node[:memory]
        vb.cpus   = node[:cpus]
      end
    end
  end

  config.vm.define "monitor" do |last|
    last.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/playbook.yml"
      ansible.limit = "all"
      ansible.host_key_checking = "false"
      ansible.compatibility_mode = "2.0"
      ansible.groups = {
        "nextcloud" => ["nextcloud-1", "nextcloud-2"]
      }
      ansible.host_vars = {
        "nextcloud-1" => {
          "keepalived_state" => "MASTER",
          "keepalived_priority" => 110
        },
        "nextcloud-2" => {
          "keepalived_state" => "BACKUP",
          "keepalived_priority" => 100
        },
        "postgres-1" => {
          "postgres_role" => "primary"
        },
        "postgres-2" => {
          "postgres_role" => "replica"
        },
        "spare" => {
          "spare_ip" => "#{INTERNAL_NET}.16",
          "spare_keepalived_state" => "BACKUP",
          "spare_keepalived_priority" => 90
        }
      }
    end
  end
end
