---
- name: NGINX | Install and configure NGINX
  ansible.builtin.yum:
    name: nginx
    state: present
  become: true
  notify:
    - restart nginx
  tags:
    - nginx-install

- name: NGINX | Create nginx config file from template
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: "0644"
    owner: nginx
  become: true
  notify:
    - reload nginx
  tags:
    - nginx-configuration
