Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.ssh.username = "vagrant"
  config.ssh.insert_key = "true"

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "vvv"
    ansible.playbook = "provisioning/playbook.yml"
    ansible.become = "true"
    ansible.host_key_checking = "false"
    ansible.raw_ssh_args = ['-o', 'StrictHostKeyChecking=no']
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 256
    v.cpus = 1
  end

  config.vm.define "ns01" do |ns01|
    ns01.vm.network "forwarded_port", guest: 22, host: 2210, id: "ssh"
    ns01.vm.network "private_network", ip: "192.168.56.10"
    ns01.vm.hostname = "ns01"
  end

  config.vm.define "ns02" do |ns02|
    ns02.vm.network "forwarded_port", guest: 22, host: 2211, id: "ssh"
    ns02.vm.network "private_network", ip: "192.168.56.11"
    ns02.vm.hostname = "ns02"
  end

  config.vm.define "client" do |client|
    client.vm.network "forwarded_port", guest: 22, host: 2215, id: "ssh"
    client.vm.network "private_network", ip: "192.168.56.15"
    client.vm.hostname = "client"
  end

  config.vm.define "client2" do |client2|
    client2.vm.network "forwarded_port", guest: 22, host: 2216, id: "ssh"
    client2.vm.network "private_network", ip: "192.168.56.16"
    client2.vm.hostname = "client2"
  end
end
