---
- name: Create nextcloud database and user
  shell: |
    docker exec postgres psql -U postgres -c \
    "SELECT 1 FROM pg_roles WHERE rolname='{{ postgres_user }}'" | grep -q 1 || \
    docker exec postgres psql -U postgres -c \
    "CREATE USER {{ postgres_user }} WITH PASSWORD '{{ postgres_password }}';"

    docker exec postgres psql -U postgres -c \
    "SELECT 1 FROM pg_database WHERE datname='{{ postgres_db }}'" | grep -q 1 || \
    docker exec postgres psql -U postgres -c \
    "CREATE DATABASE {{ postgres_db }} OWNER {{ postgres_user }};"
  args:
    chdir: /opt/postgres
  changed_when: false

- name: Create replication user
  shell: |
    docker exec postgres psql -U postgres -c \
    "SELECT 1 FROM pg_roles WHERE rolname='{{ postgres_replication_user }}'" | grep -q 1 || \
    docker exec postgres psql -U postgres -c \
    "CREATE USER {{ postgres_replication_user }} WITH REPLICATION PASSWORD '{{ postgres_replication_password }}';"
  changed_when: false

- name: Create Zabbix PostgreSQL monitoring user
  shell: |
    docker exec postgres psql -U postgres -c \
    "SELECT 1 FROM pg_roles WHERE rolname='{{ zabbix_postgres_monitor_user }}'" | grep -q 1 || \
    docker exec postgres psql -U postgres -c \
    "CREATE USER {{ zabbix_postgres_monitor_user }} WITH PASSWORD '{{ zabbix_postgres_monitor_password }}' INHERIT;"
  changed_when: false

- name: Grant PostgreSQL monitoring privileges to Zabbix user
  shell: |
    docker exec postgres psql -U postgres -c \
    "GRANT pg_monitor TO {{ zabbix_postgres_monitor_user }};"
    docker exec postgres psql -U postgres -c \
    "GRANT CONNECT ON DATABASE postgres TO {{ zabbix_postgres_monitor_user }};"
    docker exec postgres psql -U postgres -c \
    "GRANT CONNECT ON DATABASE {{ postgres_db }} TO {{ zabbix_postgres_monitor_user }};"
    docker exec postgres psql -U postgres -c \
    "GRANT EXECUTE ON FUNCTION pg_catalog.pg_ls_dir(text) TO {{ zabbix_postgres_monitor_user }};"
    docker exec postgres psql -U postgres -c \
    "GRANT EXECUTE ON FUNCTION pg_catalog.pg_stat_file(text) TO {{ zabbix_postgres_monitor_user }};"
  changed_when: false
