Vagrant.configure("2") do |config|
  config.vm.define "pam" do |node|
    node.vm.box      = "ubuntu/jammy64"
    node.vm.hostname = "pam"

    node.vm.network "private_network", ip: "192.168.57.10"

    node.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus   = 2
    end

    node.vm.provision "ansible" do |ansible|
      ansible.playbook         = "ansible/provision.yml"
      ansible.host_key_checking = false
      ansible.groups = {
        "pam" => ["pam"]
      }
    end
  end
end
